[package]
name = "slosh"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sl-compiler = { path = "../sl-compiler" }
sl-liner = { git = "https://github.com/sl-sh-dev/sl-liner.git" }
slvm = { path = "../../slvm" }
#slvm = { git = "https://github.com/sstanfield/slvm.git" }

